### ISSUE TITLE
Troubleshooting with plugin Background Removal

### ISSUE THREAD

**Issue by webmasternic** [royshil/obs-backgroundremoval#131]
Hello, With my MAC I had a problem with the plugin Background Removal. I have installed OBS v. 28.1.2 and after I put the plugin's files in /Applications/OBS.app/Contents/. When I use a filter on the video capture I don't see the specific option in the application.Why, OBS does not take into consideration the plugin download. Thanks for your help.

**Comment by chibimara** [comment]
Yes, I am having the same issue. Any help or direction on getting this to work would be greatly appreciated! Not sure what I'm missing here.

**Comment by st203** [comment]
I'm having the same issue on OBS 28.1.2.

**Comment by anatale** [comment]
Check out this PR to make it work. https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.4.3-umireon

**Comment by webmasternic** [comment]
I downloaded the plugin and installed it in the appropriate directory but I don't see the plugin in OBS.

**Comment by anderfo** [comment]
I'm on OBS 29.0.0 (mac) and have the same issue, the filter won't show up. I also tried what @anatale suggested above, but I found no difference.

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with M1 OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

**Comment by anderfo** [comment]
> try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

Thanks for the hard work!
Sadly, after installing the filter (on MacOS Ventura 13.2.1) I still don't find it in OBS. I looked into the OBS.app\Contents\PlugIns\ directory without finding any signs of it there either, so I wonder where it ended up :)

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled? The author of this issue is not here anymore.

**Comment by royshil** [comment]
closing stale issue
